name: Release Drafter

on:
  push:
    branches:
      - main
    paths:
      - "**"
      - "!docs/**"
      - "!.github/**"
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate CalVer version
        id: calver
        run: |
          export CALVER=$(date "+%Y.%-m")
          echo "version=${CALVER}" >> $GITHUB_OUTPUT
          echo "Version set to ${CALVER}"
      - uses: release-drafter/release-drafter@v6.0.0
        with:
          name: ${{ steps.calver.outputs.version }}
          tag: ${{ steps.calver.outputs.version }}
          version: ${{ steps.calver.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}