# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '0,15,30,45 * * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - name: Close Stale Issues
      uses: actions/stale@v10.1.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 30
        days-before-close: 14
        stale-issue-message: No activity for 30 days, this issue will close in 14 days if no further activity
        stale-pr-message: No activity for 30 days, this PR will close in 14 days
        stale-issue-label: stale
        stale-pr-label: stale
        exempt-issue-labels: no-stale
        exempt-pr-labels: no-stale
        
